version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    environment:
      env_file: .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  celery:
    build: ./fundas-api
    command: celery worker -B -l info -A app.blueprints.api.tasks
    env_file:
      - '.env'
    volumes:
      - './fundas-api:/fundas-api'
      - 'C:\Users\Toto\Dropbox\Watchlist:/dropbox'

  api:
    build: ./fundas-api
    environment:
      env_file: .env
    volumes:
      - './fundas-api:/fundas-api'
      - 'C:\Users\Toto\Dropbox\Watchlist:/dropbox'
    ports:
      - '8000:8000'

  ui:
    build: ./fundas-ui
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
      - './fundas-ui:/app'
      - 'node_modules:/app/node_modules'
    ports:
      - '3000:3000'

volumes:
  postgres:
  redis:
  node_modules:
