version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    env_file:
      - '.env'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'

  api:
    build: ./fundas-api
    env_file:
      - '.env'
    volumes:
      - './fundas-api:/fundas-api'
      - '/Users/Udit/Dropbox/Watchlist:/dropbox'
    ports:
      - '8000:8000'

  ui:
    build: ./fundas-ui
    env_file:
      - '.env'
    volumes:
      - ./fundas-ui:/app
      - /app/node_modules
      - node_modules:/node_modules
    ports:
      - '3000:3000'



#  celery:
#    build: .
#    command: celery worker -B -l info -A app.blueprints.contact.tasks
#    env_file:
#      - '.env'
#    volumes:
#      - '.:/fundas-app'

volumes:
  postgres:
  redis:
  node_modules:
